apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdr-users.fullname" . }}
  labels:
    {{- include "fdr-users.labels" . | nindent 4 }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador/v2
      kind: Mapping
      host: {{ .Values.ambassador.host }}
      grpc: true
      prefix: /grpc/
      name: {{ include "fdr-users.fullname" . }}-grpc-mapping
      service: {{ include "fdr-users.fullname" . }}:{{ .Values.service.grpc }}
      ---
      apiVersion: getambassador/v2
      kind: Mapping
      host: {{ .Values.ambassador.host }}
      grpc: false
      prefix: /api/
      name: {{ include "fdr-users.fullname" . }}-http-mapping
      service: {{ include "fdr-users.fullname" . }}:{{ .Values.service.port }}
      cors:
        origins: *
        methods: POST, GET, OPTIONS
        headers: Content-Type
        credentials: true
        exposed_headers: X-Custom-Header
        max_age: "86400"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fdr-users.selectorLabels" . | nindent 4 }}
{{/*---*/}}
{{/*apiVersion: getambassador.io/v2*/}}
{{/*kind:  Mapping*/}}
{{/*metadata:*/}}
{{/*  name:  catch-all*/}}
{{/*spec:*/}}
{{/*  host: {{ .Values.ambassador.host }}*/}}

{{/*  prefix: /api/*/}}
{{/*  name: {{ include "fdr-users.fullname" . }}-http-mapping*/}}
{{/*  service: {{ include "fdr-users.fullname" . }}:{{ .Values.service.port }}*/}}
{{/*  cors:*/}}
{{/*    origins: **/}}
{{/*    methods: POST, GET, OPTIONS*/}}
{{/*    headers: Content-Type*/}}
{{/*    credentials: true*/}}
{{/*    exposed_headers: X-Custom-Header*/}}
{{/*    max_age: "86400"*/}}