{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fdr-users.serviceAccountName" . }}
  labels:
{{ include "fdr-users.labels" . | nindent 4 }}
{{- end -}}
