apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdr-users.fullname" . }}
  labels:
    {{- include "fdr-users.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fdr-users.selectorLabels" . | nindent 4 }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: {{ include "fdr-users.fullname" . }}-http-mapping
spec:
  prefix: /users/
  service: {{ include "fdr-users.fullname" . }}:{{ .Values.service.port }}
  add_linkerd_headers: true
  cors:
    origins: '*'
    methods: POST, GET, OPTIONS
    headers: Content-Type
    credentials: true
    exposed_headers: X-Custom-Header
    max_age: "86400"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: {{ include "fdr-users.fullname" . }}-grpc-mapping
spec:
  prefix: /users-grpc/
  add_linkerd_headers: true
  service: {{ include "fdr-users.fullname" . }}:{{ .Values.service.grpc }}
  grpc: True
