package auth

import (
	"github.com/go-kit/kit/log"
	"github.com/gorilla/sessions"
	"github.com/stretchr/testify/assert"
	"github.com/thethan/fdr-users/pkg/gothic"
	"github.com/thethan/fdr-users/pkg/gothic/yahoo"
	"net/http"
	"testing"
)

func TestService_GetCredentialInformation(t *testing.T) {
	logger := log.NewNopLogger()
	yProvider := yahoo.New("", "", "")
	service := NewService(logger, yProvider)
	t.Run("getting information from string", func(t *testing.T) {
		cookieString := "MTU4NDUwMDc5NHxEdi1CQkFFQ180SUFBUkFCRUFBQV9nVTBfNElBQVFaemRISnBibWNNQndBRmVXRm9iMjhHYzNSeWFXNW5EUDRGRlFELUJSRWZpd2dBQUFBQUFBRF9USlRKeXFSYUFvVGZKZUhmVlZuT21mNVFOR3FxT1RnUDZVQ0RPQnpuS1k5SFUyMzYzWnU2ellXN0NpSVd3UmViLU0tSlgxRGwyZXJwLTFRaE5NM2Z2MzRsVTQxMVkxa1AySjVVNDRobFlfOXJUQlpVa2I4Z2VDOWdSdkVmOTYtc3E4R0E0anJfblRmNF91aGJ6cmpsVFVybWdvdDNVVWJwM3FPM09QLVZROE9fSDhueGNPenVZYm51NDVYNi1pMDlPdDF5Y1BRWU5DNGt1U1dqWGlnS0hrZms2M3NVV0gxR2had21SclRwUDlwX0x6aE9zaERrTlFRWmloZFlfXzRMOW92aXYwajVpNVNMWkVESnZPY3dLUkFjeF80UDh4Y3BMek9BOHpfMERfWVhLZjgxNi1fT2VScUhHY1JvbjhEdmJNekJfX01aSlFqOGJucUxhSW9jR2pvZjMzU1JJVDE5ZWFjNkJNYjVlZkFqeXlaRURwZGh6OG9hTXZWN29MWmp1TDZTTWlCXzhpallEOWZkTjF1akJWSUMxY1hZclVEdUUtYnpSVjJfcU92cHg0blBNakRQN3RpQzRmUjlDbDhjbGQteGtON2lCZkthUFF3TllYNFlzQlR1T1RjUlhzYWs1bTNoS3c4cl9uNmxSc3l5eFRsQjBSVHlZYUh5aWtmeW1TQmNXRVNzM2t1dFFIRmNGVy1CcERCQ1ZiWmVzY3BGOFJNTzVITmlKQ2FKLWtLN3VjbkVSN3UtYjVRY2daVy1mSUtXSlFsOE1QcHpnc19iRTFNWGRDdm1mVHZjc0ZrTTdJblJrMU16T0tqSHhYRWxvVEFaVExaS2I0R0RtVWRpeW91V3JYZkZ4SWxYdzJBblFUWnRUVnoxYzFGNVdJeHl1aFpnSFJiMkdLdkdYQmxTTk1NNFJoMndKTTJlMC1KcFc1dHg3clV4VWVremszbmlUZmZIQ1phWG1mR0JYLXBUSERsblVkcHF2dFhTUzFBSkhhRVNVNjc1QWVFOUJobHdmZHlfSUFjdU10bm5zM1lsdU9PZFdPOWdIeU5Da29IM3FDQjJzX01uV3hESmphQ3Exb29xU1R1OFZLY0tkdy1ncjE1OHVrR1Z5UlZ0bTFwQ3V3MXU3aXVNNmxIRlo2dDUxeFJVNGJodjZwV3lQd2RZeDRvWUZkbGUydUpkWHJwdFVvUVJSelZKaHlhT3huc3BSYVYyamp1NE5MT2tNSTJFX0JWZzlqZzZFOEU0TlR2TUwxdFpacTVoTU44Mmp5ZXp5OHlySHhjYXlaOHRnVmhGaEh0Z3FYWDdYckk2aVc0dnExV2xLU09xLVpCOTM4SWVJcWdpbE83R3ZSQXZaMTg3MENPTmppay15d2hyOU82aGtNOWhQWjRLbnF5NFpBOUZxS3ZiTlNLNlRXQUtSNUdQTGF4dWVQUW1rN3ZfZ2VjT0pBSVRycjRHWlpFWHlNVjEzdHQ5RHhRalZuWjZLNXVaeTNOaFUxaTZkWElwRF8xM0VhZ0tnUWlVci15NGxyVnZHRkhpUDNPczQ5bkNPUzdYcG4zMFdCYlpWN2FzRmpwelpWWnlCaWp5WEhVdlVXWXY1RzFxcDdIQ29TOWNrM21EYnR3SnFyblc3aXRmTWdDSWowbmNhcFh5REZZeU5iS2hYa216VmtxOHZfSkc2cVpNNXlUU0Q0eDVDNG5WdTFxMWxieUh3b3AzVENjcV9qREFSOGJtRWE5czBjRnY4NzRKQzRJMWxoU2gzNllNanIweGZCR1BROWJnV0xLTFFSOXJ4dG9UTDAwRXctSWdaVlNLdVVfOGxOTkhhUXBRdExNN2RrdWdLR0dNUktHNU1BOGo2d2tKc0E3MlVZX09aNjVHVEFXRTFkSVgyV3EyOU9OSTAwZnBEN2VhZmZ4d0VJbjRIT3ZwVzJlMzBEeVREZWF5Ynd0VGtRZEhYVnVmdm54YlNDeHI3MWhscVctRVkzUTlQcV9xenVXclQ5QlJJUkRFV0JsMnpkRVZZNFhHNFV3aDJORzBra1JYa3l2SFNnYnJ0YVdVSHZjSEw5Vlc1dWUwNkpTRGZYbHpweDhuR3hRUXpOWGZMOFBmMGpMdDZPd3AydTQ2OFZXYlNfaWkyUGNoZUJTU3RBenNvMC1VMlREbGVoV3E0cHp3c25rczUxZXRzcE9hQi1YUDA0LVR0RTAxQkRPUFR0OG5FaWZ4bnpqMWs3aTRPUDJOczk4VWpWRWt4OUpuN2tKRXBfXy1Ed0FBX184QkFBRF9fNS1fcm9WZ0JnQUF87WmRR1QGM2gPdP4Ps4eR8MlY9mU_2ypiW0z3PGmI7iY="
		req, err := http.NewRequest(http.MethodGet, "/", nil)
		if err != nil {
			assert.Nil(t, err )
			t.FailNow()
		}
		cookie := sessions.NewCookie(gothic.SessionName, cookieString, &sessions.Options{})

		req.AddCookie(cookie)

		user, err := service.getUserFromHttp(req)
		if err != nil {
			assert.Nil(t, err, err.Error() )
			t.FailNow()
		}
		assert.Equal(t, "yahoo", user.Provider)
	})
}
