package auth

import (
	"github.com/go-kit/kit/log"
	"github.com/gorilla/sessions"
	"github.com/stretchr/testify/assert"
	"github.com/thethan/fdr-users/pkg/gothic"
	"github.com/thethan/fdr-users/pkg/gothic/yahoo"
	"net/http"
	"testing"
)

func TestService_GetCredentialInformation(t *testing.T) {
	logger := log.NewNopLogger()
	yProvider := yahoo.New("", "", "")
	service := NewService(logger, yProvider)
	t.Run("getting information from string", func(t *testing.T) {
		cookieString := "MTU4MzcxOTc0M3xEdi1CQkFFQ180SUFBUkFCRUFBQV9nVV9fNElBQVFaemRISnBibWNNQndBRmVXRm9iMjhHYzNSeWFXNW5EUDRGSUFELUJSd2Zpd2dBQUFBQUFBRF9iSlRIcnF0YXVvWGZ4ZExxbmNYR1pKYTBkVFV4WUlMQkJCTjFKVVNZNUJ4c29GVHZYdHFuZEhyVi12V1B4cWR2ZE1hX0xtQmJTOGQ2WEg0dTVicU95OC12WF9GWUllMVFWRDF5eE9Vd0lPblFfUnJpYlMyeFh6T2NOcmlzMFpfdl85SzJndjBhVmRudnJFWVBwV3ZZcDVUVkNaWnhMN1FOVTF4M2xNNWtQVGVibjU1OHhxZGlXNjFpdmw2S20zaTZsSnl0YnRyb3F2UWFHMkRzbHVMdUd2cktHWHI2RWZwbWwtSUJxOTFDd3ZDVTV2ODNGTVdvR1diVkROTTEydWJxOTkteVh6ajR3c1F2VE16amZvMlhJNXZqZkoySG9mdmpfSVdKMndMbjVYX2NQX3BmbVBoM3ZYX1l5emowQzR6V1k0U18weUdEXzgyWE5WN2hiOENxb3MyaW1NemdycXlQTGxZQ19NcWprQlZhQUNMOV9obHZIZ0RSR0Fsa2JObXJGTjlaRkNqZjlKdUpTOWQyak52M0ZvTGtTTzN6QnVybkxyTXBGWkxtRjg1XzRmemxyd3RJVTdnc3I2R0JfZVhuWWlTNGlGRkhRSEJENjhnekNJOEhWU3NmRnRCOWZCMUFZRHd3SVlxeVR5bEVwMTdUQ3E2a2xSUGdvblROaG9fMmVlY1REbUlQTENCSldULVBQSWJKV010LUU0Y3VSZkZ5eTlIU3p0ODFSRmFXUFVfTWp2U3JVR3FFSWFsVEpKM0tfdW1Hck5zeVI1SEVIZXo1NmhSU0VfQU1KNkM2eUpqNHctZlR0MUtrb19ZcHU4aURsSDVWSUxObENTYlc2RWo2TEo3R3Vod0RGUzVFN3llT2UyOE1OYTFpbFBZb2l5c1N0RmNiTnlJaVdGUGNMcGlpWnpsS04xR3YyV0dyV2VLYThrVU9QVGJBZVhnZHZkdGZhMGZqTEtkakRmVnVuV1FyYVU5bXJjWkQ1RDdiTG9RSDRqRUU3V05DSHpCNE53dHVEcF9vbzBEQnJzYlg5enVZb3BuTGp5dVBlVUlmUU1RR1FDWVZ5ZVZNYjg0cmhoUlNrMmJXLTVOaHppeXRXMEk2TndHNVFsTU5UY0pRRjdqWjVlN2N3MEstY2p0Z1pRdVpnenhEVkdWZTlxQXJKSEI0TTJha1pWM3BITm5iZXVuUllZMDhCeTQ4WHJVTHl1UkJ5MllRT0s5RVF5RWdTZzhwWE91V2lMUXZFZmFuVDg2RDRsZWlmczJSb2JGeF9hYmJCcGNRdWthWWhha2Jjbmh5dmM1bFJKRDZMNE1rRlVMYm1tTGJpTmJKRzR1YVc3OXlZZ2lwSU5ac25GZDF4aG1jdV9qbWRhYkJ3bEJ2dVlURG1kQUxvZEwxY1RQWHBxUU9FdnJNSm1GQXNKam53amN4V3pzbGUwanAzeld5djZzN1dVaWpva3FxNlhWQ3RIa2RhX3RWMlFJVWFSLUxsVGNsbFF2NXVMMjBEeTAzZlczZE12NkE3LUlkek14UWllN0hpTFdQS2p1dFliNkdETDMxWlN4WWRzSWJKeV9aMUlmUGhJSTgtT21nck01WW1XNmlIVWdiT0pjdUNOTHVWTlFjWjVMNVZIcV82Z3BhVnVsMFdtZUczMFFuQ054Z2tzdjRiTXo4WVpFMU54UnNoWmFUemdkbWJzbU1VLTJ1UDdEa2xTVFVVWkxMcGlyTFc0RnN0N2sxcUYzNktKOHhEVWtmSTJCdHh6aHk4bE5xQXBabXpTQnFEV0U3OGNqSDNRQmxENVhYYmMzR2kyZzY1Q0pUelBiVTBtMkxCZ08tREQ0OVNua2lpZlpSSHlLUzItbUU2X2UybDExMGVjelJpQlNZNzg5NlJYX3VfR2tsaTdTOXdZZHBlMks0MDJVMThsUmVuZFNVWm56UTMzQi1PVk1zM1BtbndKSWh3WkxtZkgybURJLUtlNkhSYnloRGFVaURObjhMRlhVRUx0LVYwV005cE5DcXpHMnU5R1VlSHlJMVRUbGlMUzhYOGUzckNRUDM0Zm5Cd0RDaU9qWUZ5c0Y1MENjam9lX01rU2pNVnRkS29nRWdTUEJ1ZmxfLXVsZ3duLUZTX3JNNFFFaXd4RVZ0QXE5V0dqNHhoTGtsSkVzNmdiaWhnckQxbE5MRjktVnBpTldiSzNNNkJxSnhiclJiUGFqeGtmbkZINkt3ajlVTUY3QmVmaTRZaXFIZktQNk5zaThVXzBIWkh4UkhNQnFucnRjckdWNy1fUjhBQUFEX193RUFBUF9fMEI3dEdITUdBQUE9fHaK42ytD3mfrsRfKrIf_K3-BjgafrTnJ17xvVmFE8am"
		req, err := http.NewRequest(http.MethodGet, "/", nil)
		if err != nil {
			assert.Nil(t, err )
			t.FailNow()
		}
		cookie := sessions.NewCookie(gothic.SessionName, cookieString, &sessions.Options{})

		req.AddCookie(cookie)

		user, err := service.getUserFromHttp( req)
		if err != nil {
			assert.Nil(t, err )
			t.FailNow()
		}
		assert.Equal(t, "yahoo", user.Provider)
	})
}
